In [50]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Business Understanding
Europese data reporten

# Data Understanding
De data is ons aangeleverd in een `excel` bestanden:

1. In welk format is de data aangeleverd?
In een excel bestanden

2. Hoe kun je de databron benaderen vanuit python?
Door de methode van panda read_excel()

3.Data exploreren
a informatie over de database

Tabellen (evt. collections) staan er in de bestanden?
Per jaar zijn er 2 exel bestanden geleverd. 

Welke kolommen (variabelen) vinden we terug in elke tabel? Kun je aan elke kolom betekenis geven?

-Method name : Naam van het meetapparaat

-N	: Aantal labs

-Mean :  Gemiddelde van HbA1c waarde

-Bias	:  Absolute toe- of afname van de hoeveelheid mmol/mol ten opzichte van de werkelijke waarde

-CV	:  Laat zien wat de spreiding is de metingen

-Sample	: Hoeveelste meting in het jaar

-Reference Value	
-Year : Welk jaar

-Source	: Amerikaans of Europese data
    
-Type :  Vers of bevroren bloed



• Wat is het aantal records per tabel? (verdeeld in vers of bevroren bloed)

2016: fresh 48/ frozen 32

2017: fresh 42/ frozen 38

2018: fresh 56 / frozen 46

2019: fresh 62/ frozen 48

2020: fresh 78 / frozen 64

• Welke datatypes vinden we terug in de tabellen?
floats en objects

• Zijn er lege cellen?
ja, een paar lege cellen

b. Vul dit evt. aan met beschrijvende statistiek (spreidings- en centrummaten), kijk alvast vooruit naar Kmeans

c. Visualiseer de data op een slimme manier, kijk alvast vooruit naar K-means

In [51]:
df16fresh = pd.read_excel("data/2016_Fresh_EurA1c_report_converted.xlsx")
df16frozen = pd.read_excel("data/2016_Frozen_EurA1c_report_converted.xlsx")
df17fresh = pd.read_excel("data/2017_Fresh_EurA1c_report_converted.xlsx")
df17frozen = pd.read_excel("data/2017_Frozen_EurA1c_report_converted.xlsx")
df18fresh = pd.read_excel("data/2018_Fresh_EurA1c_report_converted.xlsx")
df18frozen = pd.read_excel("data/2018_Frozen_EurA1c_report_converted.xlsx")
df19fresh = pd.read_excel("data/2019_Fresh_EurAAA1c_report_converted.xlsx")
df19frozen = pd.read_excel("data/2019_Frozen_EurAAA1c_report_converted.xlsx")
df20fresh= pd.read_excel("data/2020_Fresh_EurA1c_report_converted.xlsx")
df20frozen = pd.read_excel("data/2020_Frozen_EurA1c_report_converted.xlsx")

In [52]:
df16 =  pd.concat([df16frozen, df16fresh], ignore_index=True)

In [53]:
df16.nlargest(n=10, columns=['CV'])

,Method,N,Mean,Bias,CV,Sample,Refrence Value,Year,Source,Type
51,Medinor,6,52.6,-5.3,17.1,Sample 2,0,2016,EURA1c,Fresh
50,Medinor,6,38.2,-4.1,12.1,Sample 1,0,2016,EURA1c,Fresh
14,Not Known,14,41.6,-0.7,8.7,Sample 1,0,2016,EURA1c,Frozen
2,Beckman Coulter AU,7,43.7,1.4,7.9,Sample 1,0,2016,EURA1c,Frozen
15,Not Known,18,57.0,-0.9,7.4,Sample 2,0,2016,EURA1c,Frozen
1,Abbott Architect Enzymatic,24,53.6,-4.3,6.8,Sample 2,0,2016,EURA1c,Frozen
75,Tosoh G7,27,59.5,1.6,6.2,Sample 2,0,2016,EURA1c,Fresh
35,Abbott Architect Immuno,6,55.3,-2.6,6.1,Sample 2,0,2016,EURA1c,Fresh
8,Bio-Rad Variant,38,43.8,1.5,5.8,Sample 1,0,2016,EURA1c,Frozen
40,Beckman Coulter AU,26,41.4,-0.9,5.6,Sample 1,0,2016,EURA1c,Fresh

In [54]:
df16['Refrence Value'] = df16['Refrence Value'].astype(float)
df16.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Method          80 non-null     object
 1   N               80 non-null     int64
 2   Mean            80 non-null     float64
 3   Bias            80 non-null     float64
 4   CV              80 non-null     float64
 5   Sample          80 non-null     object
 6   Refrence Value  80 non-null     float64
 7   Year            80 non-null     int64
 8   Source          80 non-null     object
 9   Type            80 non-null     object
dtypes: float64(4), int64(2), object(4)
memory usage: 6.4+ KB

In [58]:
df16['Reference Value']= df16['Sample'].apply(lambda x: 42.3 if (x == 'Sample 1') else 57.9) 
df16.head()

,Method,N,Mean,Bias,CV,Sample,Refrence Value,Year,Source,Type,Reference Value
0,Abbott Architect Enzymatic,24,38.5,-3.8,5.2,Sample 1,0.0,2016,EURA1c,Frozen,42.3
1,Abbott Architect Enzymatic,24,53.6,-4.3,6.8,Sample 2,0.0,2016,EURA1c,Frozen,57.9
2,Beckman Coulter AU,7,43.7,1.4,7.9,Sample 1,0.0,2016,EURA1c,Frozen,42.3
3,Beckman Coulter AU,6,59.7,1.8,5.0,Sample 2,0.0,2016,EURA1c,Frozen,57.9
4,Bio-Rad D10,37,41.4,-0.9,5.5,Sample 1,0.0,2016,EURA1c,Frozen,42.3

In [60]:
rv_dict = {
    'Sample 1': 42.3, 
    'Sample 2': 57.9
}

df16['Reference Value'] = df16['Sample'].map(rv_dict)
df16.head()

,Method,N,Mean,Bias,CV,Sample,Refrence Value,Year,Source,Type,Reference Value
0,Abbott Architect Enzymatic,24,38.5,-3.8,5.2,Sample 1,0.0,2016,EURA1c,Frozen,42.3
1,Abbott Architect Enzymatic,24,53.6,-4.3,6.8,Sample 2,0.0,2016,EURA1c,Frozen,57.9
2,Beckman Coulter AU,7,43.7,1.4,7.9,Sample 1,0.0,2016,EURA1c,Frozen,42.3
3,Beckman Coulter AU,6,59.7,1.8,5.0,Sample 2,0.0,2016,EURA1c,Frozen,57.9
4,Bio-Rad D10,37,41.4,-0.9,5.5,Sample 1,0.0,2016,EURA1c,Frozen,42.3

In [65]:
for index, row in df16.iterrows():
    if row['Sample'] == 'Sample 1':
        row['Refrence Value'] = 42.3
    else: 
        row['Refrence Value'] = 57.9
        
    
df16.head()

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
51
53
55
57
59
61
63
65
67
69
71
73
75
77
79

,Method,N,Mean,Bias,CV,Sample,Refrence Value,Year,Source,Type,Reference Value
0,Abbott Architect Enzymatic,24,38.5,-3.8,5.2,Sample 1,0.0,2016,EURA1c,Frozen,42.3
1,Abbott Architect Enzymatic,24,53.6,-4.3,6.8,Sample 2,0.0,2016,EURA1c,Frozen,57.9
2,Beckman Coulter AU,7,43.7,1.4,7.9,Sample 1,0.0,2016,EURA1c,Frozen,42.3
3,Beckman Coulter AU,6,59.7,1.8,5.0,Sample 2,0.0,2016,EURA1c,Frozen,57.9
4,Bio-Rad D10,37,41.4,-0.9,5.5,Sample 1,0.0,2016,EURA1c,Frozen,42.3